jobs:
## PROD deployment job for BOX
#  - name: box-prod-aws
#    type: deploy
#    steps:
#      - IN: box-rel
#        switch: off
#      - IN: box-p-params
#      - IN: env-prod-aws
#      - IN: box-p-scaler
#      - IN: box-p-kick

## DR deployment job for BOX
#  - name: box-dr-dcl
#    type: dclDeploy
#    steps:
#      - IN: box-test-aws
#        trigger: false
#      - IN: box-dr-params
#      - IN: env-dr-dcl
