jobs:
# PROD deployment job for BOX
  - name: box-prod-aws
    type: deploy
    steps:
      - IN: box-test-aws
        trigger: false
      - IN: box-p-params
      - IN: env-prod-aws
#      - IN: box-p-kick
#      - IN: box-p-scaler

## DR deployment job for BOX
#  - name: box-dr-dcl
#    type: dclDeploy
#    steps:
#      - IN: box-test-aws
#        trigger: false
#      - IN: box-dr-params
#      - IN: env-dr-dcl
